# Generated by Django 2.2.5 on 2022-10-10 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='description',
            new_name='دسکریپشن',
        ),
    ]
