# Generated by Django 2.2.5 on 2022-10-10 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20221010_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='دسکریپشن',
            new_name='description',
        ),
    ]
